# Docker compose to test the scraper on local docker
version: "3.8"

services:
  scraper:
    env_file:
      - .env
    build: .
    environment:
      - KUBECONFIG=/app/kubeconfig
    volumes:
      - ./logs:/app/logs
      - ~/.kube/config:/app/kubeconfig
    network_mode: "host"
      
