apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: node-exporter
  name: node-exporter-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: node-exporter-cron-job
            image: hmx098/node-exporter-scraper:latest
            imagePullPolicy: Always
            env:
              - name: ENV
                valueFrom:
                  configMapKeyRef:
                    key: ENV
                    name: node-exporter-cron-job-config
              - name: NAMESPACE
                valueFrom:
                  configMapKeyRef:
                    key: NAMESPACE
                    name: node-exporter-cron-job-config
              - name: PORT
                valueFrom:
                  configMapKeyRef:
                    key: PORT
                    name: node-exporter-cron-job-config
              - name: SERVICE_NAME
                valueFrom:
                  configMapKeyRef:
                    key: SERVICE_NAME
                    name: node-exporter-cron-job-config
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: AWS_ACCESS_KEY_ID
                    name: node-exporter-s3-secrets
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: AWS_SECRET_ACCESS_KEY
                    name: node-exporter-s3-secrets
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  secretKeyRef:
                    key: AWS_DEFAULT_REGION
                    name: node-exporter-s3-secrets
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: S3_BUCKET
                    name: node-exporter-s3-secrets
              
            volumeMounts:
              - name: logs-volume
                mountPath: /app/logs
          
          volumes:
            - name: logs-volume
              persistentVolumeClaim:
                claimName: node-exporter-cron-pvc

          serviceAccountName: node-exporter-cron-job-account
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 10
          